### ISSUE TITLE
Unknown options are ignored by the walkmod tool

### ISSUE THREAD

**Issue by ftomassetti** [rpau/walkmod-core#14]
I tried passing several options life `-X` or `-Abc` and walkmod seems to accept them without complaining. I was expecting an error to be reported.

I did that because I was trying to enable more verbosity using -X like I do with maven.

**Comment by rpau** [comment]
Yes, you are right. The shell should be improved to control the available options.

**Comment by rpau** [comment]
Completely fixed at commit 6f2e8b52798c6a09c7623b27931dad4fadc0bdb2
