### ISSUE TITLE
Specifying custom formatting options

### ISSUE THREAD

**Issue by ftomassetti** [rpau/walkmod-core#16]
I wonder how can I use walkmod with two projects having different formatting settings.
From what I understood there is a file (walkmod/config/formatter.xml) controlling the formatter but that file is global, so if I change it and run walkmod for project A then I have to change it according to the settings of project B before run it on B. It would great to have an option to specify the formatter settings to use when launching walkmod. Maybe it is already possible and I missed it.

**Comment by rpau** [comment]
Hi,

Yes, you can customize your formatting settings for project. This  link (http://walkmod.com/manual#formatting) explains how.

**Comment by ftomassetti** [comment]
thanks and sorry for missing this!

**Comment by ftomassetti** [comment]
BTW I noticed there is a minor typo in the example in the manual:
```xml
<writer path="src" type=
"org.walkmod:walkmod-java-formatter-plugin:writer" >
<param name="configFile">myconfig.xml<param> 
</writer> 
```
the closing tag should be `</param>` not `<param>`

**Comment by rpau** [comment]
Thank you! Solved :)
