### ISSUE TITLE
Code conventions to improve PRs

### ISSUE THREAD

**Issue by abelsromero** [rpau/walkmod-core#30]
Should we define some coding conventions?
It's a thing I don't like because I think it supresses part of the developers creativity, but I use Intellj defaults which differs from eclipse defaults and GitHub has some issues compating PR's files.
For instance I use spaces and you use tabs, I don't follow the 80 chars rule...also seems to be a problem with linebreaks, even when I use windows8, I guess intellj is using unix format.

As a side note, I use eclipse at work and intellj for personal stuff, so I could switch. But I preffer the second because gralde/groovy works (gradle in eclipse is in baby-steps right now), better maven integration, better GitHub integration, and finally because most people uses it in OS so I decided to move after wasting time changing the formatting of eclipse to be the same.

You're the lead so you define how to proceed. I will only ask for one thing, could we change the 80 char limit to 120.

**Comment by rpau** [comment]
Yes, of course. I will add the formatter file into the walkmod.xml file setting the limit to 120

**Comment by rpau** [comment]
Done into the dev branch
